### ISSUE TITLE
Все еще поддерживается ?

### ISSUE THREAD

**Issue by Potracheno** [serhiicherepanov/Magento-EMS#2]
Не работает с Magento ver. 1.9.2.3, в частности не выводится при чекауте, сообщение об ошибке то же. Кроме того ваш модуль выдают за свой на https://www.magentocommerce.com/magento-connect/ems-shipping-module.html

**Comment by serhiicherepanov** [comment]
@VoteForNavalny видимо вы забыли настроить адрес магазина, я обновил readme.  Проверил на последней версии, все работает как и прежде.
